--- 
language: scala
script: "sbt ++$TRAVIS_SCALA_VERSION coverage test"

jdk:
  - oraclejdk8

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0

sudo: false # Enable new travis container-based infrastructure

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a3d21b4ef5b88d789383
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
